### ISSUE TITLE
APT yarn.list Corruption

### ISSUE THREAD

**Issue by stevewest15** [Jarli01/xenorchestra_installer#121] opened 2024-01-04 20:57 UTC
**Describe the bug**
After running the update script (ie curl https://raw.githubusercontent.com/Jarli01/xenorchestra_updater/master/xo-update.sh | bash ), apt-get update returns an error about a "Malformed entry 1 in list file /etc/apt/sources.list.d/yarn.list"

**To Reproduce**
1. From the command line, I run the following command which completes with no errors:

```
# apt-get update
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://deb.debian.org/debian bullseye-updates InRelease
Hit:3 http://security.debian.org/debian-security bullseye-security InRelease
Hit:4 https://dl.yarnpkg.com/debian stable InRelease   
Reading package lists... Done

```
2. Next, I run the update script:

```
# curl https://raw.githubusercontent.com/Jarli01/xenorchestra_updater/master/xo-update.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6485  100  6485    0     0   275k      0 --:--:-- --:--:-- --:--:--  275k
   installed : v18.19.0 (with npm 10.2.3)
Stopping xo-server...
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
main: line 266: sudo: command not found
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
gpg: [stdout]: write error: Broken pipe
gpg: [stdout]: write error: Broken pipe
gpg: filter_flush failed on close: Broken pipe
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
Checking for Yarn package...
Checking for Yarn update...
E: Malformed entry 1 in list file /etc/apt/sources.list.d/yarn.list ([option] not assignment)
E: The list of sources could not be read.
E: Malformed entry 1 in list file /etc/apt/sources.list.d/yarn.list ([option] not assignment)
E: The list of sources could not be read.
E: Malformed entry 1 in list file /etc/apt/sources.list.d/yarn.list ([option] not assignment)
E: The list of sources could not be read.
Checking for missing dependencies...
Checking for Repo change...
Checking xen-orchestra...
Current branch master
Current version 5.132.0 / 5.133.0
Current commit 0f00c7e393e97bb1f950f65e30dbba0cba13c264 2024-01-04 11:33:30 +0100
0 updates available
Restarting xo-server...
```

3. Now if I run the apt-get update again, it returns an error which wasn't present at step 1 when I ran the same command:

```
# apt-get update
E: Malformed entry 1 in list file /etc/apt/sources.list.d/yarn.list ([option] not assignment)
E: The list of sources could not be read.
```

**Expected behavior**
apt-get update shouldn't break after running the xoce update script.

**Screenshots**
![image](https://github.com/Jarli01/xenorchestra_installer/assets/13159246/e9b93aab-bd5a-4f15-b097-651b81762d22)

**Desktop/Server details (please complete the following information):**
 - OS: Linux XOCE 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux

**Additional context**
To fix the issue, I followed these [instructions](https://classic.yarnpkg.com/en/docs/install#debian-stable) to update yarn.list:
![image](https://github.com/Jarli01/xenorchestra_installer/assets/13159246/8747d42e-ef87-41e5-b82c-803a6b1bd7e9)

However if I run the XOCE update script, it will break apt-get update once again with the same error above.

**Confirm XOCE services are running**
Please run ```systemctl status xo-server.service``` and paste the resulting output below. 

```
# systemctl status xo-server.service
â xo-server.service - XO Server
     Loaded: loaded (/lib/systemd/system/xo-server.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2024-01-04 15:38:05 EST; 16min ago
   Main PID: 16308 (node)
      Tasks: 11 (limit: 19138)
     Memory: 153.8M
        CPU: 5.749s
     CGroup: /system.slice/xo-server.service
             ââ16308 /usr/local/bin/node ./dist/cli.mjs

Jan 04 15:38:10 XOCE xo-server[16308]:     errno: -113,
Jan 04 15:38:10 XOCE xo-server[16308]:     code: 'EHOSTUNREACH',
Jan 04 15:38:10 XOCE xo-server[16308]:     syscall: 'connect',
Jan 04 15:38:10 XOCE xo-server[16308]:     address: '10.10.10.73',
Jan 04 15:38:10 XOCE xo-server[16308]:     port: 443,
Jan 04 15:38:10 XOCE xo-server[16308]:     originalUrl: 'https://10.10.10.73/jsonrpc',
Jan 04 15:38:10 XOCE xo-server[16308]:     url: 'https://10.10.10.73/jsonrpc',
Jan 04 15:38:10 XOCE xo-server[16308]:     call: { method: 'session.login_with_password', params: '* obfuscated *' }
Jan 04 15:38:10 XOCE xo-server[16308]:   }
Jan 04 15:38:10 XOCE xo-server[16308]: }
```

**Provide the output of journalctl logs**
Please run ```journalctl -u xo-server -f -n 50``` and paste the resulting output below. 

```
root@XOCE:~# journalctl -u xo-server -f -n 50
-- Journal begins at Sun 2022-05-08 23:42:54 EDT. --
Jan 04 15:38:08 XOCE xo-server[16308]: strict mode: required property "tokenURL" is not defined at "#/anyOf/1/properties/advanced" (strictRequired)
Jan 04 15:38:08 XOCE xo-server[16308]: 2024-01-04T20:38:08.322Z xo:plugin INFO successfully register auth-github
Jan 04 15:38:08 XOCE xo-server[16308]: 2024-01-04T20:38:08.322Z xo:plugin INFO successfully register auth-google
Jan 04 15:38:08 XOCE xo-server[16308]: 2024-01-04T20:38:08.322Z xo:plugin INFO successfully register auth-ldap
Jan 04 15:38:08 XOCE xo-server[16308]: 2024-01-04T20:38:08.322Z xo:plugin INFO successfully register auth-oidc
Jan 04 15:38:08 XOCE xo-server[16308]: 2024-01-04T20:38:08.322Z xo:plugin INFO successfully register auth-saml
Jan 04 15:38:08 XOCE xo-server[16308]: 2024-01-04T20:38:08.322Z xo:plugin INFO successfully register netbox
Jan 04 15:38:08 XOCE xo-server[16308]: 2024-01-04T20:38:08.322Z xo:plugin INFO successfully register test-plugin
Jan 04 15:38:08 XOCE xo-server[16308]: 2024-01-04T20:38:08.322Z xo:plugin INFO successfully register transport-icinga2
Jan 04 15:38:08 XOCE xo-server[16308]: 2024-01-04T20:38:08.322Z xo:plugin INFO successfully register transport-nagios
Jan 04 15:38:08 XOCE xo-server[16308]: 2024-01-04T20:38:08.322Z xo:plugin INFO successfully register transport-xmpp
Jan 04 15:38:08 XOCE xo-server[16308]: 2024-01-04T20:38:08.322Z xo:plugin INFO successfully register usage-report
Jan 04 15:38:08 XOCE xo-server[16308]: 2024-01-04T20:38:08.322Z xo:plugin INFO successfully register transport-slack
Jan 04 15:38:08 XOCE xo-server[16308]: 2024-01-04T20:38:08.322Z xo:plugin INFO successfully register web-hooks
Jan 04 15:38:08 XOCE xo-server[16308]: 2024-01-04T20:38:08.322Z xo:plugin INFO successfully register backup-reports
Jan 04 15:38:08 XOCE xo-server[16308]: 2024-01-04T20:38:08.322Z xo:plugin INFO successfully register transport-email
Jan 04 15:38:08 XOCE xo-server[16308]: 2024-01-04T20:38:08.343Z xo:plugin INFO successfully register audit
Jan 04 15:38:08 XOCE xo-server[16308]: 2024-01-04T20:38:08.344Z xo:plugin INFO successfully register load-balancer
Jan 04 15:38:08 XOCE xo-server[16308]: 2024-01-04T20:38:08.344Z xo:plugin INFO successfully register perf-alert
Jan 04 15:38:08 XOCE xo-server[16308]: 2024-01-04T20:38:08.409Z xo:plugin INFO successfully register sdn-controller
Jan 04 15:38:10 XOCE xo-server[16308]: 2024-01-04T20:38:10.832Z xo:xo-mixins:xen-servers WARN failed to connect to XenServer {
Jan 04 15:38:10 XOCE xo-server[16308]:   host: '10.10.10.75',
Jan 04 15:38:10 XOCE xo-server[16308]:   error: Error: connect EHOSTUNREACH 10.10.10.75:443
Jan 04 15:38:10 XOCE xo-server[16308]:       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
Jan 04 15:38:10 XOCE xo-server[16308]:       at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:128:17) {
Jan 04 15:38:10 XOCE xo-server[16308]:     errno: -113,
Jan 04 15:38:10 XOCE xo-server[16308]:     code: 'EHOSTUNREACH',
Jan 04 15:38:10 XOCE xo-server[16308]:     syscall: 'connect',
Jan 04 15:38:10 XOCE xo-server[16308]:     address: '10.10.10.75',
Jan 04 15:38:10 XOCE xo-server[16308]:     port: 443,
Jan 04 15:38:10 XOCE xo-server[16308]:     originalUrl: 'https://10.10.10.75/jsonrpc',
Jan 04 15:38:10 XOCE xo-server[16308]:     url: 'https://10.10.10.75/jsonrpc',
Jan 04 15:38:10 XOCE xo-server[16308]:     call: { method: 'session.login_with_password', params: '* obfuscated *' }
Jan 04 15:38:10 XOCE xo-server[16308]:   }
Jan 04 15:38:10 XOCE xo-server[16308]: }
Jan 04 15:38:10 XOCE xo-server[16308]: 2024-01-04T20:38:10.834Z xo:xo-mixins:xen-servers WARN failed to connect to XenServer {
Jan 04 15:38:10 XOCE xo-server[16308]:   host: '10.10.10.73',
Jan 04 15:38:10 XOCE xo-server[16308]:   error: Error: connect EHOSTUNREACH 10.10.10.73:443
Jan 04 15:38:10 XOCE xo-server[16308]:       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
Jan 04 15:38:10 XOCE xo-server[16308]:       at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:128:17) {
Jan 04 15:38:10 XOCE xo-server[16308]:     errno: -113,
Jan 04 15:38:10 XOCE xo-server[16308]:     code: 'EHOSTUNREACH',
Jan 04 15:38:10 XOCE xo-server[16308]:     syscall: 'connect',
Jan 04 15:38:10 XOCE xo-server[16308]:     address: '10.10.10.73',
Jan 04 15:38:10 XOCE xo-server[16308]:     port: 443,
Jan 04 15:38:10 XOCE xo-server[16308]:     originalUrl: 'https://10.10.10.73/jsonrpc',
Jan 04 15:38:10 XOCE xo-server[16308]:     url: 'https://10.10.10.73/jsonrpc',
Jan 04 15:38:10 XOCE xo-server[16308]:     call: { method: 'session.login_with_password', params: '* obfuscated *' }
Jan 04 15:38:10 XOCE xo-server[16308]:   }
Jan 04 15:38:10 XOCE xo-server[16308]: }
```

**Provide answers to these questions:**
* Is this a fresh install or an upgrade? Upgrade
* Version of XOCE server and web interface you're running: Xen Orchestra, commit [0f00c](https://github.com/vatesfr/xen-orchestra/commit/0f00c7e393e97bb1f950f65e30dbba0cba13c264)
Master, commit [0f00c](https://github.com/vatesfr/xen-orchestra/commit/0f00c7e393e97bb1f950f65e30dbba0cba13c264)
* What OS is XOCE running on? Debian 5.10.92-1 (2022-01-18)
* A link to the ISO you've used as as the server (so we can verify/troubleshoot)
* What method did you use to install XOCE (xo_install.sh, manual installation, etc)
* What specific XOCE page you're on, and what specific element you're interacting with to trigger the error
* If a stacktrace is provided in the error, include that too.
* Any errors that appear in your browser's error console.
* Include what you've done so far in the installation, and if you got any error messages along the way.
* Indicate whether or not you've manually edited any data directly.

Thank You,

SW

**Comment by Danp2** [comment] 2024-01-05 00:01
Hi Steve,

I'll see if I can reproduce this. In the mean time, please provide the following --

- Output from `node -v` (should be `v18.xx`)
- Output from `cat /etc/apt/sources.list.d/yarn.list`

**Comment by stevewest15** [comment] 2024-01-05 00:31
@Danp2 Thank you for your assistance! Here is the items you requested:

```
# node -v
v18.19.0

# cat /etc/apt/sources.list.d/yarn.list
deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian/ stable main
```

**Comment by Danp2** [comment] 2024-01-05 13:32
I believe the issue is related to the use of `sudo` in both the install and update scripts. Since this command isn't found by default in Debian, the `gpg` commands are failing as shown in your output above. I am in the process of testing both scripts with this command removed.

**Comment by Danp2** [comment] 2024-01-05 16:19
I ran some basic tests with both Debian and Ubuntu, and everything worked ask expected for me. There are two PRs waiting for @Jarli01 to review. @stevewest15 If you want to test, these are the commands that I used --

- Install XO
 `bash -c "$(curl https://raw.githubusercontent.com/Jarli01/xenorchestra_installer/dp_sudo/xo_install.sh)"`

- Update XO
`bash -c "$(curl https://raw.githubusercontent.com/Jarli01/xenorchestra_updater/dp_sudo/xo-update.sh)"`

Note that the above changes won't fix a previously "broken" install.

**Comment by Jarli01** [comment] 2024-01-05 16:55
All PR's have been approved, thanks @Danp2!

**Comment by Danp2** [comment] 2024-01-05 17:16
@stevewest15 Please retry with a fresh VM and let us know if you encounter any issues.

**Comment by Danp2** [comment] 2024-01-10 18:19
@stevewest15 Please try without installing sudo when you have a chance.

**Comment by stevewest15** [comment] 2024-01-10 18:42
@Danp2 Thank you for the update! I just tried running the XO installer on a clean Debian 11 without 'sudo' package and so far no issues trying to run apt update/upgrade after running XO update script: 

`root@XOCE:/# sudo bash
bash: sudo: command not found

root@XOCE:/# bash -c "$(curl https://raw.githubusercontent.com/Jarli01/xenorchestra_installer/master/xo_install.sh)"
...
Tasks:    25 successful, 25 total
Cached:    0 cached, 25 total
  Time:    1m12.377s

Done in 72.64s.
Ignoring xo-server-test plugin
Created symlink /etc/systemd/system/multi-user.target.wants/xo-server.service → /lib/systemd/system/xo-server.service.


Installation complete, open a browser to:
10.10.10.208

Default Login:admin@admin.net Password:admin

Don't forget to change your password!

root@XOCE:/# apt-get update
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Hit:4 https://dl.yarnpkg.com/debian stable InRelease
Reading package lists... Done

root@XOCE:/# apt-get upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

root@XOCE:/# curl https://raw.githubusercontent.com/Jarli01/xenorchestra_updater/master/xo-update.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6477  100  6477    0     0   421k      0 --:--:-- --:--:-- --:--:--  421k
     copying : node/18.19.0
   installed : v18.19.0 (with npm 10.2.3)
Stopping xo-server...
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
Checking for Yarn package...
Checking for Yarn update...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
yarn is already the newest version (1.22.19-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Checking for missing dependencies...
Checking for Repo change...
Checking xen-orchestra...
Current branch master
Current version 5.132.0 / 5.133.0
Current commit 9388b5500c79b593bfe3ccdf0c791315d21e2b7b 2024-01-10 17:17:42 +0100
0 updates available
Restarting xo-server...

root@XOCE:/# apt-get update
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://deb.debian.org/debian bullseye-updates InRelease
Hit:3 http://security.debian.org/debian-security bullseye-security InRelease
Hit:4 https://dl.yarnpkg.com/debian stable InRelease
Reading package lists... Done

root@XOCE:/# apt-get upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`

**Closed** 2024-01-10 20:48 UTC
