### ISSUE TITLE
Fresh Install 18.04.1 - xo fail to start

### ISSUE THREAD

**Issue by shwetkprabhat** [Jarli01/xenorchestra_installer#31] opened 2018-08-17 11:35 UTC
#### Expected Behavior

The xo server should start after a fresh install and reboot.

-----

#### Actual Behavior

XO server fails to start

-----

#### Confirm XOCE services are running

```systemctl status xo-server.service```
 systemctl status xo-server.service
● xo-server.service - XO Server
   Loaded: loaded (/lib/systemd/system/xo-server.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2018-08-17 11:30:30 UTC; 5s ago
  Process: 1462 ExecStart=/usr/local/bin/node ./bin/xo-server (code=exited, status=203/EXEC)
 Main PID: 1462 (code=exited, status=203/EXEC)

Aug 17 11:30:30 xoc systemd[1]: xo-server.service: Service hold-off time over, scheduling restart.
Aug 17 11:30:30 xoc systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 5.
Aug 17 11:30:30 xoc systemd[1]: Stopped XO Server.
Aug 17 11:30:30 xoc systemd[1]: xo-server.service: Start request repeated too quickly.
Aug 17 11:30:30 xoc systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 17 11:30:30 xoc systemd[1]: Failed to start XO Server.

#### Provide the output of journalctl logs

```journalctl -u xo-server -f -n 50```
 -- Logs begin at Fri 2018-08-17 11:00:52 UTC. --
Aug 17 11:24:07 xoc systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 17 11:24:07 xoc systemd[1]: xo-server.service: Service hold-off time over, scheduling restart.
Aug 17 11:24:07 xoc systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 5.
Aug 17 11:24:07 xoc systemd[1]: Stopped XO Server.
Aug 17 11:24:07 xoc systemd[1]: xo-server.service: Start request repeated too quickly.
Aug 17 11:24:07 xoc systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 17 11:24:07 xoc systemd[1]: Failed to start XO Server.
Aug 17 11:30:29 xoc systemd[1]: Started XO Server.
Aug 17 11:30:29 xoc systemd[1421]: xo-server.service: Failed to execute command: No such file or directory
Aug 17 11:30:29 xoc systemd[1421]: xo-server.service: Failed at step EXEC spawning /usr/local/bin/node: No such file or directory
Aug 17 11:30:29 xoc systemd[1]: xo-server.service: Main process exited, code=exited, status=203/EXEC
Aug 17 11:30:29 xoc systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 17 11:30:29 xoc systemd[1]: xo-server.service: Service hold-off time over, scheduling restart.
Aug 17 11:30:29 xoc systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 1.
Aug 17 11:30:29 xoc systemd[1]: Stopped XO Server.
Aug 17 11:30:29 xoc systemd[1]: Started XO Server.
Aug 17 11:30:29 xoc systemd[1432]: xo-server.service: Failed to execute command: No such file or directory
Aug 17 11:30:29 xoc systemd[1432]: xo-server.service: Failed at step EXEC spawning /usr/local/bin/node: No such file or directory
Aug 17 11:30:29 xoc systemd[1]: xo-server.service: Main process exited, code=exited, status=203/EXEC
Aug 17 11:30:29 xoc systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 17 11:30:30 xoc systemd[1]: xo-server.service: Service hold-off time over, scheduling restart.
Aug 17 11:30:30 xoc systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 2.
Aug 17 11:30:30 xoc systemd[1]: Stopped XO Server.
Aug 17 11:30:30 xoc systemd[1]: Started XO Server.
Aug 17 11:30:30 xoc systemd[1442]: xo-server.service: Failed to execute command: No such file or directory
Aug 17 11:30:30 xoc systemd[1442]: xo-server.service: Failed at step EXEC spawning /usr/local/bin/node: No such file or directory
Aug 17 11:30:30 xoc systemd[1]: xo-server.service: Main process exited, code=exited, status=203/EXEC
Aug 17 11:30:30 xoc systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 17 11:30:30 xoc systemd[1]: xo-server.service: Service hold-off time over, scheduling restart.
Aug 17 11:30:30 xoc systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 3.
Aug 17 11:30:30 xoc systemd[1]: Stopped XO Server.
Aug 17 11:30:30 xoc systemd[1]: Started XO Server.
Aug 17 11:30:30 xoc systemd[1452]: xo-server.service: Failed to execute command: No such file or directory
Aug 17 11:30:30 xoc systemd[1452]: xo-server.service: Failed at step EXEC spawning /usr/local/bin/node: No such file or directory
Aug 17 11:30:30 xoc systemd[1]: xo-server.service: Main process exited, code=exited, status=203/EXEC
Aug 17 11:30:30 xoc systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 17 11:30:30 xoc systemd[1]: xo-server.service: Service hold-off time over, scheduling restart.
Aug 17 11:30:30 xoc systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 4.
Aug 17 11:30:30 xoc systemd[1]: Stopped XO Server.
Aug 17 11:30:30 xoc systemd[1]: Started XO Server.
Aug 17 11:30:30 xoc systemd[1462]: xo-server.service: Failed to execute command: No such file or directory
Aug 17 11:30:30 xoc systemd[1462]: xo-server.service: Failed at step EXEC spawning /usr/local/bin/node: No such file or directory
Aug 17 11:30:30 xoc systemd[1]: xo-server.service: Main process exited, code=exited, status=203/EXEC
Aug 17 11:30:30 xoc systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 17 11:30:30 xoc systemd[1]: xo-server.service: Service hold-off time over, scheduling restart.
Aug 17 11:30:30 xoc systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 5.
Aug 17 11:30:30 xoc systemd[1]: Stopped XO Server.
Aug 17 11:30:30 xoc systemd[1]: xo-server.service: Start request repeated too quickly.
Aug 17 11:30:30 xoc systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 17 11:30:30 xoc systemd[1]: Failed to start XO Server.
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh
- Version of XOCE server and web interface you're running
Fresh install latest version
- What OS is XOCE running on?
Ubuntu 18.04.1
- What method you used to install XOCE (xo_install.sh, manual installation, etc)
xo_install.sh
- What specific XOCE page you're on, and what specific element you're interacting with to trigger the error
n/a
- If a stacktrace is provided in the error, include that too.
n/a
- Any errors that appear in your browser's error console.
n/a
- Include what you've done so far in the installation, and if you got any error messages along the way.
installation exit code was sucessful
- Indicate whether or not you've manually edited any data directly.
n/a

**Comment by Danp2** [comment] 2018-08-17 11:40
Thanks for the report. There appears to be a change in behavior with Node that is affecting the installation. See #30 for additional discussion.

**Comment by PDWDSVC** [comment] 2018-08-17 11:40
Hi shwetkprabhat,
you are having the same issue as i had.

From your logging file:
Aug 17 11:30:30 xoc systemd[1452]: xo-server.service: Failed at step EXEC spawning /usr/local/bin/node: No such file or directory

please read my issue  https://github.com/Jarli01/xenorchestra_installer/issues/30 for steps in resolving this manually.

Best regards

**Comment by Jarli01** [comment] 2018-08-17 11:42
Was just about to post the same thing.

**Comment by Danp2** [comment] 2018-08-17 13:06
Duplicate of #30

**Closed by Danp2** 2018-08-17 13:06 UTC

**Comment by Jarli01** [comment] 2018-08-17 13:17
Fixed in #30 with the recent updates, please test again and let us know if you encounter any other issues. 

Thanks!
