### ISSUE TITLE
Systemd service creation causes memory leak

### ISSUE THREAD

**Issue by ghost** [Jarli01/xenorchestra_installer#66] opened 2020-02-16 22:34 UTC
**Describe the bug**
By creating a systemd service for xo-server there is a memory leak which causes OOM Killer to kill the NodeJS instance running xo-server once all available memory and swap space in consumed. The causes first run Delta and Continuous Replication jobs to fail with "Interrupted" on VM disks larger than the memory and swap space combined.

**To Reproduce**
1. Create a VM with a disk of 500GB 4GB RAM and 2 vCPU's
2. Fill the disk with at least 250GB of data
3. Create at Delta Backup task for the VM
4. Run the backup task
5. Task fails with "Interrupted"

**Expected behavior**
Backup task completes without OOM killer killing the xo-server service and restarting it.

**Screenshots**

**Desktop/Server details (please complete the following information):**
 - OS: Debian 10 (Buster)
 - XO-Server 5.56.2
 - XO-Web 5.56.2
 - Node JS 8.17.0

**Provide answers to these questions:**
* Is this a fresh install or an upgrade? - Fresh
* Version of XOCE server and web interface you're running - Stated Above
* What OS is XOCE running on? - Stated Above
* A link to the ISO you've used as as the server (so we can verify/troubleshoot)
   https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-10.3.0-amd64-netinst.iso
* What method did you use to install XOCE (xo_install.sh, manual installation, etc) - xo_install.sh
* What specific XOCE page you're on, and what specific element you're interacting with to trigger the error - Backups - Starting newly created delta backup job
* If a stacktrace is provided in the error, include that too. - N/A
* Any errors that appear in your browser's error console. - None
* Include what you've done so far in the installation, and if you got any error messages along the way. - Removed the systemd service which xo_install.sh sets up and used "forever" and "forever-service"
* Indicate whether or not you've manually edited any data directly. - No

I have found the resolution to this issue and I am only creating this bug report so that you can make edits to your xo_install.sh script to resolve this issue for other users using your installer.

The solution is to replace the service creation section of your installer with the following:
yarn global add forever
yarn global add forever-service
cd /<path>/<to>/xo-server/bin/
forever-service install orchestra -r <username used to run xo-server> -s xo-server

**Comment by Jarli01** [comment] 2020-02-16 22:45
Can you create a PR that can be merged and tested?

**Comment by Danp2** [comment] 2020-02-17 15:10
@Jarli01 Need to first prove that using systemd is truly an issue

**Comment by Jarli01** [comment] 2020-02-17 15:17
Exactly, this is the first time of heard of this issue.

**Comment by Jarli01** [comment] 2020-02-17 15:59
@jonmike992001 

Since you have what appears to be a working solution, please submit a PR so we can test it with your recommended changes. 

I've not encountered this issue in the past (with VM's much larger than described) so we need to be very thorough in our testing of this and make sure we're pinpointing the correct problem.

**Comment by jonmike992001** [comment] 2020-02-17 21:16
Let me see if I can get a PR for you. Been some time since I've used git to do that.

**Comment by LPJon** [comment] 2020-02-17 21:41
Hello, I believe I have to github accounts. I was using the wrong one as "jonmike992001". Please know that I will be submitting the pull request from this account: LPJon

**Comment by LPJon** [comment] 2020-02-17 22:54
Ok....I have submitted a pull request. Please advise me if it was incorrectly done.

**Comment by Danp2** [comment] 2020-02-19 01:53
FWIW, I'm trying to replicate this issue with my existing, fully updated, XO VM (Ubuntu 19.10, Node v8.16.0, 2 vCPUs, 2GB). I created a VM with a 500GB drive and filled it with 294GB of data. The export is 85% done, and I haven't observed / encountered any issues. I'll retest with a brand new XO install and report back.

**Comment by Danp2** [comment] 2020-02-19 02:57
Built a new XO VM using the Debian ISO you linked above. Still not seeing the behavior that you've described. Please tell us more about your setup, such as --
- Have you installed the guest tools in the XO VM?
- What type of remote are you using for the backup destination?
- Etc

Also, how are you ending up with Node 8.17? I got 8.16.2 when I ran the script. Have you tried using this earlier version to see if the issue can be reproduced with it?

**Comment by LPJon** [comment] 2020-02-19 05:01
I've installed node 8.17.0 by changing the script to install it, but have used 8.16.0, 8.16.1, and 8.16.2. Didn't matter which version was installed still had the same result.

Servers:
(Both Sets of servers have Broadcom NICs)
3 Dell M710HD's/Intel Xeon CPU E5645@2.40GHz with a 4GB\s Fiber Data Backend (Fiber Channel HBA LVM Storage Repository)
2 HP Proliant DL360 G6/Intel Xeon CPU E5530@2.40GHz with Chelsio 10GBe NICs directly attached to NFS v4 server (NFS v4 Repository)

Backup Remote:
NFS v4 

OS:
XCP-ng 8.0 on all servers

VM:
4 vCPU's
8GB RAM
55GB Hard Drive
No guest tools Installed and with guest tools installed produced same result. 

The build with "forever-service" works with both of these setups perfectly.

Please let me know if there is any specific information you would like. I will surely get it for you.

Tip: Watch the memory in terminal by using "systemctl status xo-server" (Your Current xo_install.sh Script Installation). I have also had this happen with an HP Proliant ML350p Gen 8

**Comment by LPJon** [comment] 2020-02-19 05:36
I also wanted to ask. What's the reasoning behind building the service file? Why not use what's in the instructions for installing XOCE. Was there a specific reason a decision was made not to?

**Comment by Jarli01** [comment] 2020-02-19 13:35
IIRC the always running portion wasn't a part of the instructions back when I started this project and we needed a way to make sure XO started at boot etc. 

We can certainly re-evaluate it now that it is in the [documentation.](https://xen-orchestra.com/docs/from_the_sources.html#always-running)

**Comment by Danp2** [comment] 2020-02-19 13:50
I wrote this portion of the script and it was designed to mimic the way this was implemented in XOA. Changing it would mean that we would have to also change the update script, and I wouldn't recommend doing this until we can confirm the source of the memory leak.

@LPJon Have you tried a different backup target?

**Comment by LPJon** [comment] 2020-02-19 18:15
@Danp2 Yes, I have also tried a local backup target as well as a local backup target which is actually mounted as NFS v4/v3 by the OS and not XOCE. I also changed NICS to Intel from Broadcom in several tests to be sure it wasn't NIC related. I can also say that this hardware is not the latest and greatest. It may be related to older hardware. I have literally spent since November 2019 til February 2020 troubleshooting this problem on all the hardware I've mentioned. What I don't understand is why it doesn't have any issues for you. The installs were out of the box nothing special (No desktop just ssh and system utilities). I tested it with direct to hardware installations and VM installations. It's just very very strange. Can I as what your test hardware is? 

@Jarli01 I see... I was only wondering what the reason was and that makes perfect sense.

**Comment by Danp2** [comment] 2020-02-19 19:58
@LPJon I have a PowerEdge R620 that I use for all my work.

**Comment by LPJon** [comment] 2020-02-19 21:20
@Danp2 That's in the same classification of servers I'm testing on. Do you test your storage locally or through a network switch? My setup is making backups through a data network. I might see if I can make a diagram for you....may help?

**Comment by Danp2** [comment] 2020-02-19 21:29
@LPJon  I'm backing up to an NFS share on NAS. The server and the NAS are attached to the same switch.

**Comment by LPJon** [comment] 2020-02-19 21:35
That's the same setup I'm using. The switch is a Cisco 2960s 1GB switch. Ya know I'm just curious....what version of `systemd` are you using? There was just a new update released I believe yesterday or the day before when Debian 10.3 came out.

**Comment by Jarli01** [comment] 2020-02-19 21:39
The individual packages are going to be system dependent. We always recommend you "stay current" not just with XO-web and XO-server but with your distribution packages as well.

**Comment by LPJon** [comment] 2020-02-19 21:51
@Jarli01 That's true and I totally agree. However, I found the solution to my problem just before that update was released. It's possible it may have been fixed in that update. That's the only reason I asked. I'm really not trying to make a stink about all of this and am perfectly fine with you leaving your script alone. My situation might be an edge case for some off the wall reason. I was really more than anything just wanting to spread awareness. I have no idea why this would only effect our server systems across so many different types of servers. There isn't anything special or complicated about our system. In fact it is very generic.

I totally agree that staying up to date is a must. Just dumb-founded.....but I guess as long as it's working for us that's what matters.

**Comment by Jarli01** [comment] 2020-02-19 22:04
@LPJon I completely understand and wasn't looking to insinuate or anything of the like. 

There could be a myriad of things that can causes issues, and certainly this script could be one of them. We just do our best to factually pinpoint that issue before we push a change. As it is @Danp2 and I are really the only maintainers of this repo - dan often does the heavy lifting. 

Hopefully if systemd updates fix the issue we don't have to change anything (as it would require we also update the updater script.)

Please let us know.

**Comment by LPJon** [comment] 2020-02-19 22:20
@Jarli01 I know that you weren't. Just feeling bad for what seems like a waste of your time and Dan's. I will try and test Debian 10.3 again with your script and see what happens. My last install was Debian 10.3 but with the changes I found to work on Debian 10.2 and not with your current script. Debian 10.2 worked with your script but would intermittently fail the backup with "Interrupted". Debian 9 would consistently fail with "Interrupted". Ubuntu 16.04  and 18.04 would also do the same. I'm really starting to believe that either I have missed some small detail or that I'm an edge case and that's just the way that it is. Please don't waste large amounts of time on this because I have even found forums where XOA is considering taking the forever project out of the official documentation [here](https://xcp-ng.org/forum/topic/2359/build-from-source-question/4) which was back in December of 2019.

**Comment by Jarli01** [comment] 2020-02-19 22:34
No worries, this could be a legitimate issue that needs to be fixed. 

It could also be some configuration issue on your switches, servers, storage, vm package, vm network, firewall settings etc. 

In short - it is worth at least looking into to see if we can't find a fix or send it upstream to fix a potential issue there.

**Comment by LPJon** [comment] 2020-02-20 03:48
@Danp2 Are you the Danp from the XCP-ng forums?

**Comment by Danp2** [comment] 2020-02-20 12:40
@LPJon Yep... that's me. 😉

**Comment by Jarli01** [comment] 2020-02-20 13:08
> @LPJon Yep... that's me. 😉

He's way cuter in person, lol.

**Comment by Danp2** [comment] 2020-02-20 13:28
@Jarli01 👅

**Closed** 2020-04-03 17:58 UTC
Labels: triaging
