### ISSUE TITLE
error on yarn

### ISSUE THREAD

**Issue by babatundebusari** [Jarli01/xenorchestra_installer#35] opened 2018-08-19 20:01 UTC
```
[1/5] Validating package.json...
error @: The engine "yarn" is incompatible with this module. Expected version "^1.7.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
yarn run v1.3.2
$ scripts/run-script --parallel build
module.js:549
    throw err;
    ^

Error: Cannot find module 'promise-toolbox'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/xen-orchestra/scripts/run-script:4:32)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by babatundebusari** [comment] 2018-08-19 20:33
fixed by installing a few dependent packages and some OS cleanup

**Comment by Jarli01** [comment] 2018-08-19 22:29
Please answer the questions in the issues template.

**Comment by babatundebusari** [comment] 2018-08-19 22:42
Ubuntu 16.04 LTS


XOCE service not running

```
● xo-server.service - XO Server
   Loaded: loaded (/etc/systemd/system/xo-server.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Sun 2018-08-19 18:39:22 EDT; 2min 22s ago
  Process: 31516 ExecStart=/usr/local/bin/node ./bin/xo-server (code=exited, status=200/CHDIR)
 Main PID: 31516 (code=exited, status=200/CHDIR)

Aug 19 18:39:22 xen-orchestra-5 systemd[1]: xo-server.service: Main process exited, code=exited, status=200/CHDIR
Aug 19 18:39:22 xen-orchestra-5 systemd[1]: xo-server.service: Unit entered failed state.
Aug 19 18:39:22 xen-orchestra-5 systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 19 18:39:22 xen-orchestra-5 systemd[1]: xo-server.service: Service hold-off time over, scheduling restart.
Aug 19 18:39:22 xen-orchestra-5 systemd[1]: Stopped XO Server.
Aug 19 18:39:22 xen-orchestra-5 systemd[1]: xo-server.service: Start request repeated too quickly.
Aug 19 18:39:22 xen-orchestra-5 systemd[1]: Failed to start XO Server.
```



logs from `/var/log/syslog`

```
Aug 19 18:39:21 localhost systemd[1]: Stopped XO Server.
Aug 19 18:39:21 localhost systemd[1]: Started XO Server.
Aug 19 18:39:21 localhost systemd[31505]: xo-server.service: Failed at step CHDIR spawning /usr/local/bin/node: No such file or directory
Aug 19 18:39:21 localhost systemd[1]: xo-server.service: Main process exited, code=exited, status=200/CHDIR
Aug 19 18:39:21 localhost systemd[1]: xo-server.service: Unit entered failed state.
Aug 19 18:39:21 localhost systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 19 18:39:21 localhost systemd[1]: xo-server.service: Service hold-off time over, scheduling restart.
Aug 19 18:39:21 localhost systemd[1]: Stopped XO Server.
Aug 19 18:39:21 localhost systemd[1]: Started XO Server.
Aug 19 18:39:21 localhost systemd[31510]: xo-server.service: Failed at step CHDIR spawning /usr/local/bin/node: No such file or directory
Aug 19 18:39:21 localhost systemd[1]: xo-server.service: Main process exited, code=exited, status=200/CHDIR
Aug 19 18:39:21 localhost systemd[1]: xo-server.service: Unit entered failed state.
Aug 19 18:39:21 localhost systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 19 18:39:22 localhost systemd[1]: xo-server.service: Service hold-off time over, scheduling restart.
Aug 19 18:39:22 localhost systemd[1]: Stopped XO Server.
Aug 19 18:39:22 localhost systemd[1]: Started XO Server.
Aug 19 18:39:22 localhost systemd[31512]: xo-server.service: Failed at step CHDIR spawning /usr/local/bin/node: No such file or directory
Aug 19 18:39:22 localhost systemd[1]: xo-server.service: Main process exited, code=exited, status=200/CHDIR
Aug 19 18:39:22 localhost systemd[1]: xo-server.service: Unit entered failed state.
Aug 19 18:39:22 localhost systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 19 18:39:22 localhost systemd[1]: xo-server.service: Service hold-off time over, scheduling restart.
Aug 19 18:39:22 localhost systemd[1]: Stopped XO Server.
Aug 19 18:39:22 localhost systemd[1]: Started XO Server.
Aug 19 18:39:22 localhost systemd[31514]: xo-server.service: Failed at step CHDIR spawning /usr/local/bin/node: No such file or directory
Aug 19 18:39:22 localhost systemd[1]: xo-server.service: Main process exited, code=exited, status=200/CHDIR
Aug 19 18:39:22 localhost systemd[1]: xo-server.service: Unit entered failed state.
Aug 19 18:39:22 localhost systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 19 18:39:22 localhost systemd[1]: xo-server.service: Service hold-off time over, scheduling restart.
Aug 19 18:39:22 localhost systemd[1]: Stopped XO Server.
Aug 19 18:39:22 localhost systemd[1]: Started XO Server.
Aug 19 18:39:22 localhost systemd[31516]: xo-server.service: Failed at step CHDIR spawning /usr/local/bin/node: No such file or directory
Aug 19 18:39:22 localhost systemd[1]: xo-server.service: Main process exited, code=exited, status=200/CHDIR
Aug 19 18:39:22 localhost systemd[1]: xo-server.service: Unit entered failed state.
Aug 19 18:39:22 localhost systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 19 18:39:22 localhost systemd[1]: xo-server.service: Service hold-off time over, scheduling restart.
```

**Comment by Jarli01** [comment] 2018-08-19 22:54
Can you run ```node -v``` and show me the output.

While 16.04 worked in the past, it's very out of date at this point. It might worth trying the current server distro.

**Comment by babatundebusari** [comment] 2018-08-19 22:57
```
$node -v
v8.11.4
```

**Comment by Jarli01** [comment] 2018-08-19 22:57
As for the very first reply it appears you have yarn 1.3.2 installed and the system is telling you that you need 1.7.0 or above. 

Compounded with the out of date OS my initial recommendation is to update to the current stable release.

**Comment by Jarli01** [comment] 2018-08-19 22:58
Node looks good, that's their LTS version.

**Comment by Jarli01** [comment] 2018-08-19 22:58
You might need to manually upgrade yarn.

**Comment by babatundebusari** [comment] 2018-08-19 22:59
lets be honest 16.04 LTS is not that outdated...14.04 LTS can be said to be outdated

i will try 18.04 then and see

how do i update yarn?

**Comment by Jarli01** [comment] 2018-08-19 23:00
I'm unable to test the build at the moment, but if you can provide a like to the ISO you've used I can test at some point and see what may be happening.

**Comment by babatundebusari** [comment] 2018-08-19 23:00
how do i update yarn? and after update of yarn what do i do next?

**Comment by Jarli01** [comment] 2018-08-19 23:01
https://stackoverflow.com/questions/49689174/how-to-upgrade-yarn-version-using-terminal

**Comment by babatundebusari** [comment] 2018-08-19 23:04
```
$npm upgrade --global yarn


   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 5.6.0 → 6.4.0    │
   │     Run npm i -g npm to update      │
   │                                     │
   ╰─────────────────────────────────────╯
```

and then i restarted XOCE and still same errors

**Comment by Jarli01** [comment] 2018-08-19 23:12
Please provide a link to the iso you've used and I'll test when I can.

**Comment by babatundebusari** [comment] 2018-08-19 23:16
what you mean what ISO?
OS is 16.04 LTS
not sure where ISO matters or what do you mean by ISO?

**Comment by babatundebusari** [comment] 2018-08-20 01:14
Am using xenserver hypervisor and am not sure ISO will matter here
either way that will be lot of work for you
i instead did the work and upgraded to 18.04 LTS and still not working


```
root@server:~# cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
root@server:~# node -v
v8.11.4
root@server:~# yarn -c
yarn install v1.9.4
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 0.19s.
root@server:~# yarn -v
1.9.4
root@server:~# ls -lha /opt/
total 12K
drwxr-xr-x  3 root root 4.0K Aug 19 17:56 .
drwxr-xr-x 23 root root 4.0K Aug 19 20:03 ..
drwxr-xr-x  9 root root 4.0K Aug 19 17:57 xen-orchestra
root@server:~# systemctl status xo-server.service
● xo-server.service - XO Server
   Loaded: loaded (/etc/systemd/system/xo-server.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2018-08-19 20:46:52 EDT; 24min ago
  Process: 6650 ExecStart=/usr/local/bin/node ./bin/xo-server (code=exited, status=200/CHDIR)
 Main PID: 6650 (code=exited, status=200/CHDIR)

Aug 19 20:46:52 server systemd[1]: Stopped XO Server.
Aug 19 20:46:52 server systemd[1]: Started XO Server.
Aug 19 20:46:52 server systemd[1]: xo-server.service: Main process exited, code=exited, status=200/CHDIR
Aug 19 20:46:52 server systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 19 20:46:52 server systemd[1]: xo-server.service: Service hold-off time over, scheduling restart.
Aug 19 20:46:52 server systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 5.
Aug 19 20:46:52 server systemd[1]: Stopped XO Server.
Aug 19 20:46:52 server systemd[1]: xo-server.service: Start request repeated too quickly.
Aug 19 20:46:52 server systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 19 20:46:52 server systemd[1]: Failed to start XO Server.
```

**Comment by babatundebusari** [comment] 2018-08-20 01:16
question now is how can i uninstall or wipe out all data of any installed xenorchestra so i can start from SCRATCH?
 

Am thinking there is an issue somewhere so will like to start from scratch on the same server

**Comment by babatundebusari** [comment] 2018-08-20 01:25
server 64 bit LTS iso from ubuntu website
http://releases.ubuntu.com/16.04/ubuntu-16.04.5-server-amd64.iso

**Comment by Jarli01** [comment] 2018-08-20 01:27
I'll test tomorrow and get back to you with what I find.

**Comment by babatundebusari** [comment] 2018-08-20 01:28
but i upgraded to 18.04 LTS now and not working? did you see my reply?
https://github.com/Jarli01/xenorchestra_installer/issues/35#issuecomment-414172045

**Comment by Jarli01** [comment] 2018-08-20 01:31
Just delete this VM and create a new one.

**Comment by Danp2** [comment] 2018-08-20 01:53
You could also try `sudo rm -rf /opt/xen-orchestra`

**Comment by babatundebusari** [comment] 2018-08-20 02:15
@Danp2 
did not help either 
did that several times

one thing i do know is updating this xenorchestra is ALWAYS an issue
i have never updated easily
always have one issue or the other until finally i get it to work

anyways will just create another VM to retry

**Comment by babatundebusari** [comment] 2018-08-20 04:09
ok now on another VM and still errors
I mean this is just not very reliable
jumped on another VM box and first run of the install command ended with errors

```
[/opt/xen-orchestra/packages/xo-server/src/xo-mixins/xen-servers.js] Added following polyfills:
  web.dom.iterable { "node":"6" }
  es6.symbol { "node":"6" }
  es7.symbol.async-iterator { "node":"6" }
  es6.promise { "node":"6" }

[/opt/xen-orchestra/packages/xo-server/src/xo.js] Added following polyfill:
  es6.promise { "node":"6" }
Successfully compiled 113 files with Babel.
[00:05:27] 'buildScripts' errored after 2.33 min
[00:05:27] Error: Cannot find module 'themes' from '/opt/xen-orchestra/packages/xo-web/src/xo-app'
    at /opt/xen-orchestra/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/opt/xen-orchestra/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/opt/xen-orchestra/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/opt/xen-orchestra/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/opt/xen-orchestra/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /opt/xen-orchestra/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
[00:05:27] 'build' errored after 2.37 min
* xo-web:build − Error: 1
```

**Comment by Danp2** [comment] 2018-08-20 11:44
Not sure why you are having so much troubles. FWIW, I just ran the build process and it worked without any issues.

**Comment by Jarli01** [comment] 2018-08-20 11:47
I'm just finishing the OS install now and will test within a moment as well. 

Thanks for testing @Danp2

**Comment by Jarli01** [comment] 2018-08-20 15:31
So I'm getting an error at the very end of the installation on this ISO. 


	[11:24:40] 'buildScripts' errored after 1.15 min
	[11:24:40] SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (106:0) while parsing /opt/xen-orchestra/node_modules/xo-acl-resolver/index.js while parsing file: /opt/xen-orchestra/node_modules/xo-acl-resolver/index.js
		at DestroyableTransform.end [as _flush] (/opt/xen-orchestra/node_modules/insert-module-globals/index.js:114:21)
		at DestroyableTransform.prefinish (/opt/xen-orchestra/node_modules/readable-stream/lib/_stream_transform.js:138:10)
		at emitNone (events.js:106:13)
		at DestroyableTransform.emit (events.js:208:7)
		at prefinish (/opt/xen-orchestra/node_modules/readable-stream/lib/_stream_writable.js:619:14)
		at finishMaybe (/opt/xen-orchestra/node_modules/readable-stream/lib/_stream_writable.js:627:5)
		at endWritable (/opt/xen-orchestra/node_modules/readable-stream/lib/_stream_writable.js:638:3)
		at DestroyableTransform.Writable.end (/opt/xen-orchestra/node_modules/readable-stream/lib/_stream_writable.js:594:41)
		at DestroyableTransform.onend (/opt/xen-orchestra/node_modules/readable-stream/lib/_stream_readable.js:577:10)
		at Object.onceWrapper (events.js:313:30)
	[11:24:40] 'build' errored after 1.15 min
	* xo-web:build − Error: 1
	✖ 1
	error Command failed with exit code 1.
	info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
	Created symlink from /etc/systemd/system/multi-user.target.wants/xo-server.service to /lib/systemd/system/xo-server.service.


I'm not yet sure what is causing this issue but I'll try and sort it out. @Danp2 did you use the ISO @babatundebusari provided with the link above?

**Comment by Danp2** [comment] 2018-08-20 15:39
No. My test VM was previously built using Ubuntu 18.04.1 LTS. I restored it to a pre-XO installation snapshot and then reran the install script.

**Comment by Jarli01** [comment] 2018-08-20 15:42
Ok, testing on 18.04.1 as well. This might be a compatibility issue with 16.04.5, will update in a bit.

**Comment by Jarli01** [comment] 2018-08-20 16:08
Hrm, works just fine on vBox (so it's likely hardware related). Testing the 16.04.5 iso on vBox as well.

**Comment by Jarli01** [comment] 2018-08-20 16:53
And 16.04.5 works just fine on vBox here at the office as well.

![chrome_2018-08-20_12-52-55](https://user-images.githubusercontent.com/14837699/44354517-0f07cb80-a478-11e8-9ad2-d8c00038229a.png)

**Comment by Jarli01** [comment] 2018-08-20 17:26
Are you selecting any additional services or roles during the installation besides SSH server and the default utilities?

LIke "web server" or some other such function?

**Comment by Jarli01** [comment] 2018-08-21 14:35
@babatundebusari just checking to see if you still need help with this? We've both tested and are unable to reproduce so without additional information we can't help to figure out this issue.

**Comment by Jarli01** [comment] 2018-08-22 11:49
@babatundebusari if you can provide any further logs we'd be happy to look. Until then I'm closing this issue as it isn't able to be reproduced in 3 separate instances.

**Closed by Jarli01** 2018-08-22 11:49 UTC
Labels: not-a-bug, question
