### ISSUE TITLE
installer not working anymore

### ISSUE THREAD

**Issue by payback007** [Jarli01/xenorchestra_installer#21] opened 2018-06-08 23:39 UTC
install on debian 9 not working anymore:
```
yarn run v1.7.0
$ scripts/run-script --parallel build
* complex-matcher:prebuild − yarn run clean
* value-matcher:prebuild − yarn run clean
* vhd-cli:prebuild − rimraf dist/ && index-modules --cjs-lazy src/commands
* vhd-lib:prebuild − yarn run clean
* xen-api:prebuild − rimraf dist/
* xo-cli:prebuild − rimraf dist/
* xo-collection:prebuild − rimraf dist/
* xo-common:prebuild − yarn run clean
* xo-lib:prebuild − rimraf dist/
* xo-remote-parser:prebuild − rimraf dist/
* xo-server:prebuild − index-modules src/api src/xapi/mixins src/xo-mixins && yarn run clean
* xo-server-auth-google:prebuild − rimraf dist/
* xo-server-auth-ldap:prebuild − rimraf dist/
* xo-server-auth-saml:prebuild − yarn run clean
* xo-server-backup-reports:prebuild − yarn run clean
* xo-server-cloud:prebuild − yarn run clean
* xo-server-perf-alert:prebuild − yarn run clean
* xo-server-transport-email:prebuild − rimraf dist/
* xo-server-transport-nagios:prebuild − yarn run clean
* xo-server-transport-slack:prebuild − yarn run clean
* xo-server-transport-xmpp:prebuild − yarn run clean
* xo-server-usage-report:prebuild − yarn run clean
* xo-vmdk-to-vhd:prebuild − yarn run clean
* xo-web:prebuild − yarn run clean && index-modules --auto src
* @xen-orchestra/cron:prebuild − yarn run clean
* @xen-orchestra/fs:prebuild − yarn run clean
* xo-acl-resolver:build − babel --source-maps --out-dir=dist/ src/
* xo-server-auth-github:build − NODE_ENV=production babel --source-maps --out-dir=dist/ src/
* xo-server-load-balancer:build − NODE_ENV=production babel --source-maps --out-dir=dist/ src/
* xo-cli:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
* xo-lib:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
* xo-remote-parser:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
* xo-server-auth-ldap:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
* xen-api:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
* xo-collection:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
* xo-server-auth-google:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
* xo-server-transport-email:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
bash: Zeile 45:  9713 Getötet                /usr/bin/yarn build
Killed
* complex-matcher:prebuild − Error: 137
* complex-matcher:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
Killed
* xo-common:prebuild − Error: 137
* xo-common:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
index generated src/api/index.js
index generated src/xapi/mixins/index.js
index generated src/xo-mixins/index.js
Killed
* value-matcher:prebuild − Error: 137
* value-matcher:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
Killed
* xo-server-backup-reports:prebuild − Error: 137
* xo-server-backup-reports:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
Killed
* xo-server-transport-xmpp:prebuild − Error: 137
* xo-server-transport-xmpp:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
index generated src/commands/index.jsKilled
* xo-server-cloud:prebuild − Error: 137
* xo-server-cloud:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/

* vhd-cli:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
Killed
* xo-server-transport-slack:prebuild − Error: 137
* xo-server-transport-slack:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
Killed
* xo-server-auth-saml:prebuild − Error: 137
* xo-server-auth-saml:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
Killed
* @xen-orchestra/cron:prebuild − Error: 137
* @xen-orchestra/cron:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
Created symlink /etc/systemd/system/multi-user.target.wants/xo-server.service → /lib/systemd/system/xo-server.service.
Killed
* xo-server-transport-nagios:prebuild − Error: 137
* xo-server-transport-nagios:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
Killed
* @xen-orchestra/fs:prebuild − Error: 137
* @xen-orchestra/fs:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
Killed
* xo-server-usage-report:prebuild − Error: 137
* xo-server-usage-report:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
```

**Comment by Jarli01** [comment] 2018-06-09 13:30
I'll test in a few minutes, just need to download the iso.

**Comment by Jarli01** [comment] 2018-06-09 15:27
@payback007 I was unable to reproduce these errors. 

https://i.imgur.com/plD7Q0l.png

**Comment by Danp2** [comment] 2018-06-09 16:03
I'm testing as well. This is my first time installing on Debian. Seems like the instructions should be revised since `sudo` doesn't exist in Debian.

**Comment by Danp2** [comment] 2018-06-09 16:05
I'm seeing errors prior to the `yarn run` --
```
Cloning into 'xen-orchestra'...
remote: Counting objects: 56102, done.
remote: Compressing objects: 100% (75/75), done.
remote: Total 56102 (delta 60), reused 58 (delta 34), pack-reused 55993
Receiving objects: 100% (56102/56102), 19.40 MiB | 4.04 MiB/s, done.
Resolving deltas: 100% (37190/37190), done.
yarn install v1.7.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
[6/9] ⠈ leveldown
[2/9] ⠈ dtrace-provider
[3/9] ⠈ argon2
[4/9] ⠈ bcrypt
warning Error running install script for optional dependency: "/opt/xen-orchestra/node_modules/argon2: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /opt/xen-orchestra/node_modules/argon2
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.11.2 | linux | ia32
gyp http GET https://nodejs.org/download/release/v8.11.2/node-v8.11.2-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v8.11.2/node-v8.11.2-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v8.11.2/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v8.11.2/SHASUMS256.txt
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/opt/xen-orchestra/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/xen-orchestra/node_modules/argon2/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/xen-orchestra/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/8.11.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/8.11.2',
gyp info spawn args   '-Dnode_gyp_dir=/opt/xen-orchestra/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/8.11.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/opt/xen-orchestra/node_modules/argon2',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
Traceback (most recent call last):
  File \"/opt/xen-orchestra/node_modules/node-gyp/gyp/gyp_main.py\", line 16, in <module>
    sys.exit(gyp.script_main())
  File \"/opt/xen-orchestra/node_modules/node-gyp/gyp/pylib/gyp/__init__.py\", line 545, in script_main
    return main(sys.argv[1:])
  File \"/opt/xen-orchestra/node_modules/node-gyp/gyp/pylib/gyp/__init__.py\", line 538, in main
    return gyp_main(args)
  File \"/opt/xen-orchestra/node_modules/node-gyp/gyp/pylib/gyp/__init__.py\", line 514, in gyp_main
    options.duplicate_basename_check)
  File \"/opt/xen-orchestra/node_modules/node-gyp/gyp/pylib/gyp/__init__.py\", line 130, in Load
    params['parallel'], params['root_targets'])
  File \"/opt/xen-orchestra/node_modules/node-gyp/gyp/pylib/gyp/input.py\", line 2778, in Load
    variables, includes, depth, check, True)
  File \"/opt/xen-orchestra/node_modules/node-gyp/gyp/pylib/gyp/input.py\", line 394, in LoadTargetBuildFile
    includes, True, check)
  File \"/opt/xen-orchestra/node_modules/node-gyp/gyp/pylib/gyp/input.py\", line 266, in LoadOneBuildFile
    aux_data, includes, check)
  File \"/opt/xen-orchestra/node_modules/node-gyp/gyp/pylib/gyp/input.py\", line 303, in LoadBuildFileIncludesIntoDict
    LoadOneBuildFile(include, data, aux_data, None, False, check),
  File \"/opt/xen-orchestra/node_modules/node-gyp/gyp/pylib/gyp/input.py\", line 246, in LoadOneBuildFile
    None)
  File \"/root/.node-gyp/8.11.2/include/node/common.gypi\", line 10
    'component%': 'static_library',
                                    ^
SyntaxError: invalid syntax
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/opt/xen-orchestra/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.9.0-6-686-pae
gyp ERR! command \"/usr/local/bin/node\" \"/opt/xen-orchestra/node_modules/.bin/node-gyp\" \"rebuild\"
gyp ERR! cwd /opt/xen-orchestra/node_modules/argon2
[6/9] ⠁ leveldown
[2/9] ⠁ dtrace-provider
[3/9] ⠁ argon2
[4/9] ⠁ bcrypt
error /opt/xen-orchestra/node_modules/level-party/node_modules/leveldown: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments:
Directory: /opt/xen-orchestra/node_modules/level-party/node_modules/leveldown
Output:
prebuild-install WARN install No prebuilt binaries found (target=8.11.2 runtime=node arch=ia32 platform=linux)
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.11.2 | linux | ia32
gyp http GET https://nodejs.org/download/release/v8.11.2/node-v8.11.2-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v8.11.2/node-v8.11.2-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v8.11.2/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v8.11.2/SHASUMS256.txt
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/opt/xen-orchestra/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/xen-orchestra/node_modules/level-party/node_modules/leveldown/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/xen-orchestra/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/8.11.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/8.11.2',
gyp info spawn args   '-Dnode_gyp_dir=/opt/xen-orchestra/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/8.11.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/opt/xen-orchestra/node_modules/level-party/node_modules/leveldown',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
Traceback (most recent call last):
  File "/opt/xen-orchestra/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/opt/xen-orchestra/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/opt/xen-orchestra/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/opt/xen-orchestra/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "/opt/xen-orchestra/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 130, in Load
    params['parallel'], params['root_targets'])
  File "/opt/xen-orchestra/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2778, in Load
    variables, includes, depth, check, True)
  File "/opt/xen-orchestra/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 394, in LoadTargetBuildFile
    includes, True, check)
  File "/opt/xen-orchestra/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 266, in LoadOneBuildFile
    aux_data, includes, check)
  File "/opt/xen-orchestra/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 303, in LoadBuildFileIncludesIntoDict
    LoadOneBuildFile(include, data, aux_data, None, False, check),
  File "/opt/xen-orchestra/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 246, in LoadOneBuildFile
    None)
  File "/root/.node-gyp/8.11.2/include/node/common.gypi", line 10
    'component%': 'static_library',
                                    ^
SyntaxError: invalid syntax
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/opt/xen-orchestra/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.9.0-6-686-pae
gyp ERR! command "/usr/local/bin/node" "/opt/xen-orchestra/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /opt/xen-orchestra/node_modules/level-party/node_modules/leveldown
```

**Comment by Danp2** [comment] 2018-06-09 16:12
This is the tail end of the install --
```
🎉  Successfully compiled 111 files with Babel.
Killed
* xo-web:build − Error: 137
✖ 8
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Created symlink /etc/systemd/system/multi-user.target.wants/xo-server.service → /lib/systemd/system/xo-server.service.


Installation complete, open a browser to:
192.168.1.176

Default Login:admin@admin.net Password:admin

Don't forget to change your password!
```

**Comment by Jarli01** [comment] 2018-06-09 16:15
@Danp2 I'm pretty sure at one point I had the requirements listed for a debian install, ```sudo``` nor ```curl``` are included in Debian by default. 

We also dealt with the lack of sudo with the changes that @pkutzner initially submitted and we had him adjust his commits.

**Comment by Danp2** [comment] 2018-06-09 16:22
Right... I manually installed curl, but not sudo. I just did `su` instead of the `sudo bash` line.

**Comment by Danp2** [comment] 2018-06-09 19:00
Appears to be an issue of insufficient memory. I originally created the VM with only 512MB. Bumped it to 2GB and it built without error.

Probably could add some checks to the script to enforce a minimum amount of available memory.

**Comment by Jarli01** [comment] 2018-06-09 22:57
I've never built XOCE with less than 1GB ram.  Is this really a common scenario? I guess we could make minimum requirements, but we should pull down the coast demo and see what that has as for "hardware".

**Comment by Danp2** [comment] 2018-06-09 23:04
That's fine. I just wasn't thinking when I initially created the VM. Having a memory check that abandons the installation routine would address the issue and same someone else from dealing with the same issues.

**Comment by Jarli01** [comment] 2018-06-12 15:20
Closing this and will create a project for the possibility of adding in a hardware check before proceeding with the installation.

**Closed by Jarli01** 2018-06-12 15:20 UTC
Labels: not-a-bug
